version: '3'
services:
  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
      - "8500:8500"
    volumes:
      - ./balancer/load-balancer.conf:/etc/nginx/nginx.conf:ro
      - ./balancer/conf.d:/etc/nginx/conf.d:ro
      - ./balancer/logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ng-1
      - ng-2
      - ng-3
    networks:
      - light_network
  ng-1:
    image: nginx:latest
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/conf.d:/etc/nginx/conf.d
      - ./deploy/logs/ng1:/var/log/nginx
      - ./deploy/static:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    networks:
      - light_network
  ng-2:
    image: nginx:latest
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/conf.d:/etc/nginx/conf.d
      - ./deploy/logs/ng2:/var/log/nginx
      - ./deploy/static:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    networks:
      - light_network
  ng-3:
    image: nginx:latest
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/conf.d:/etc/nginx/conf.d
      - ./deploy/logs/ng3:/var/log/nginx
      - ./deploy/static:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    networks:
      - light_network

networks:
  light_network:
    external: true